---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chnsoftw/himashana.me/
    - /bin/cp .htaccess $DEPLOYPATH 
    - /bin/cp -R assets $DEPLOYPATH 
    - /bin/cp -R components $DEPLOYPATH 
    - /bin/cp components-binder.js $DEPLOYPATH 
    - /bin/cp -R css $DEPLOYPATH 
    - /bin/cp helpers.js $DEPLOYPATH 
    - /bin/cp index.html $DEPLOYPATH 
    - /bin/cp typewriter.js $DEPLOYPATH 
